# Generated by Django 4.1.7 on 2024-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0002_treino_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='aceitou',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
