# Generated by Django 4.1.7 on 2024-05-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dias_treino_semanal',
        ),
        migrations.AddField(
            model_name='aluno',
            name='dias_treino_semanal',
            field=models.IntegerField(null=True),
        ),
    ]
